services:
  postgres:
    container_name: db
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=rtd'
      - 'POSTGRES_PASSWORD=postgres'
    ports:
      - '5432:5432'

  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '5050:80'
    depends_on:
      - postgres
